"""eSanjeevani-formatted referral text (B9) — copy-paste export only.

No live eSanjeevani API. Maps doctor brief fields to CHO-style referral blocks.
"""
from __future__ import annotations

from app.schemas.brief import DoctorBriefDTO


def brief_to_esanjeewani_text(brief: DoctorBriefDTO, *, patient_label: str = "Patient") -> str:
    lines: list[str] = [
        "=== eSanjeevani / CHO Referral Summary (SETU export) ===",
        "",
        f"Patient: {patient_label}",
        f"Chief complaint: {brief.chief_concern}",
        f"Summary: {brief.one_line}",
        "",
    ]

    if brief.referred_by or brief.referral_reason or brief.specialist_type:
        lines.append("--- Referral ---")
        if brief.referred_by:
            lines.append(f"Referred by: {brief.referred_by}")
        if brief.specialist_type:
            lines.append(f"Specialist type: {brief.specialist_type}")
        if brief.referral_reason:
            lines.append(f"Reason: {brief.referral_reason}")
        lines.append("")

    if brief.active_conditions:
        lines.append("--- Active conditions ---")
        for c in brief.active_conditions:
            since = f" (since {c.since})" if c.since else ""
            lines.append(f"• {c.condition}{since}")
        lines.append("")

    if brief.active_medications:
        lines.append("--- Current medications ---")
        for m in brief.active_medications:
            dose = f" {m.dose}" if m.dose else ""
            freq = f" — {m.frequency}" if m.frequency else ""
            lines.append(f"• {m.name}{dose}{freq}")
        lines.append("")

    if brief.recent_labs:
        lines.append("--- Recent investigations ---")
        for lab in brief.recent_labs:
            unit = f" {lab.unit}" if lab.unit else ""
            flag = f" [{lab.flag}]" if lab.flag and lab.flag != "normal" else ""
            lines.append(f"• {lab.test}: {lab.value}{unit}{flag}")
        lines.append("")

    if brief.allergies:
        lines.append("--- Allergies ---")
        for a in brief.allergies:
            sev = f" ({a.severity})" if a.severity else ""
            lines.append(f"• {a.substance}{sev}")
        lines.append("")

    if brief.priority and brief.priority.level == "review_soon":
        lines.append("--- Priority (deterministic lab flags only) ---")
        for r in brief.priority.reasons:
            lines.append(f"• {r}")
        lines.append("")

    if brief.suggested_questions:
        lines.append("--- Suggested questions for specialist ---")
        for i, q in enumerate(brief.suggested_questions, 1):
            lines.append(f"{i}. {q}")
        lines.append("")

    lines.extend(
        [
            "---",
            "Generated by SETU from patient-uploaded documents.",
            "Not a diagnosis. For practitioner review before eSanjeevani entry.",
        ]
    )
    return "\n".join(lines)
